version: "3"

services:
  postgres:
    image: postgres:12
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - local_pgdata:/var/lib/postgresql/data 
      # - ${PWD}/docker/postgres-entrypoint.sh:/docker-entrypoint-initdb.d/init-db.sh
      # - ${PWD}/docker/pg-dump.sql:/tmp/pg-dump.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: nuttipongg@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  pact-broker:
    image: pactfoundation/pact-broker:2.93.2.0
    ports:
      - "9393:9393"
      - "9292:9292"
    depends_on:
      - postgres
      - pgadmin
    environment:
      PACT_BROKER_PORT: 9292
      # PACT_BROKER_BASE_URL: pact-broker
      PACT_BROKER_DATABASE_URL: "postgres://postgres:password@postgres/postgres"
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "5"

  clean:
    build: .
    depends_on:
      - postgres
    environment:
      PACT_BROKER_DATABASE_URL: "postgres://postgres:password@postgres/postgres"
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "5"
      PACT_BROKER_DATABASE_CLEAN_DELETION_LIMIT: "500"
      PACT_BROKER_SQL_LOG_WARN_DURATION: "60"
      # Keep all prod versions, AND the latest version for every pacticipant/tag, and all versions less than 30 days old
      PACT_BROKER_DATABASE_CLEAN_KEEP_VERSION_SELECTORS: '[{"latest": true, "tag": true}, {"max_age": 30}]'
      PACT_BROKER_LOG_LEVEL: INFO
      PACT_BROKER_SQL_LOG_LEVEL: DEBUG
    entrypoint: clean

volumes:
  local_pgdata:
  pgadmin-data: